# Generated by Django 4.2.11 on 2024-03-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_externallinks'),
    ]

    operations = [
        migrations.CreateModel(
            name='PdfResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('pdf', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
